// Account Operations
export const ACCOUNT_LOGIN_SUCCESS = 100

export const ACCOUNT_REGISTER_SUCCESS = 105

export const ACCOUNT_UPDATE_SUCCESS = 111

export const ACCOUNT_LOGOUT_SUCCESS = 115

export const ACCOUNT_GET_SUCCESS = 125

export const CONTACT_GET_ALL_SUCCESS = 215

export const CONTACT_UPDATE_SUCCESS = 210

export const CONTACT_ADD_SUCCESS = 200